server:
  port: 8089

spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health, info
