version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: redis-demo
    network_mode: host
  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    container_name: redis-exporter-demo
    environment:
      REDIS_ADDR: "localhost:6379"
    network_mode: host
    depends_on:
      - redis
  kafka:
    image: landoop/fast-data-dev
    container_name: kafka-demo
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    network_mode: host
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-demo
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    network_mode: host
    depends_on:
      - kafka
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus-demo
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
