services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-demo
    network_mode: host
    depends_on:
      - kafka
  prometheus:
    image: prom/prometheus
    container_name: prometheus-demo
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
  kafka:
    image: landoop/fast-data-dev
    container_name: kafka-demo
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    network_mode: host
  query-microservice:
    build:
      context: ./query-microservice
      dockerfile: Dockerfile
    container_name: query-microservice-demo
    network_mode: host
    depends_on:
      - kafka
      - prometheus
      - zipkin
  inventory-microservice:
    build:
      context: ./inventory-microservice
      dockerfile: Dockerfile
    container_name: inventory-microservice-demo
    network_mode: host
    depends_on:
      - kafka
      - prometheus
      - zipkin
